sudo: false
language: generic
matrix:
  include:
  - os: linux
git:
  depth: false
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_install:
- bash ./includes/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
  - latexmk main
after_success:
  # - bash ./utilities/word_count.sh && cd utilities && latexmk -pdf word_count.tex
deploy:
  provider: releases
  api_key:
    secure: 689LcVKDu5UceNyR2ekTh1uCKdnlYUW8VwvSt/LwlYY1eIYzbR66klajKotRfto6M0xFu4Zo4gl46TA7AQQPHJPeHB8kVfPZ3kbCBqrvV9LiFjupSpGmvNbZkyhiWtgCdP6v728Gb5HryXGhm1uDCznqrIp6A4URw77ih3xS3STg3zO2MMRr8u9zO3GQXHcQ6NYOl77WbV6Uj6Eivpb5JGTM4UjPLZ0T8Vgc3kw4CmBP+ERVXXRqhFbhXfYh7TBDh2KLC9cESlciHSkQIZvjlY4dGdQch0BXIvc+WDwfyEVGTws5qEhV9RUvjJbM6BuFIi4gW7aORurv3e027Wt9O6ED27aZYtl+LUVsnh4FjoeGHjrvpGPZ4tB/lVqqz73rzpzz2q3V8hngv9roFIZGJ/qgECXl1oC14HyhmlyyHAm0yqOHCy5IEOJ2bRuFbIMCFAVEQpASGnU1H7Ss0MZPhXcaD2K8O9v0xum0yL7KK3ld71zpZjr9PJgC5LGiEmSyBZPVnjM1/uXw+E1BNis4uB93E32cfIQMYLfjY3bNux9h0XVelgTFw5cWGM1Lf8g+drzg9ntqv90psl7T/BZ0LvAsHjQYoDKORVOwM+SerrhiyapoJcFgSv8PlOmXaPFcqWAQTQdxZhsdcUxwcoietuj+ZrzhUnwfPH/SzSufFhY=
  file: 
    - "main.pdf"
  skip_cleanup: true
  on:
    repo: mrdavidkovacs/MasterThesis
branches:
  only:
  - master